mysql:
  enable: false
  hostname: "localhost"
  database: "minecraft"
  username: "root"
  password: "pass123"
  port: 3306

Economy:
  defaultMoney: 300

command:
  add:
    name: "add" #command name,
    usage: "&6Usage: /money add <player> <quantity>." #Error message when you use it wrongly
    permission: "rtb.economy.admin" #command permission
    alias: ["a"] #alias
  set:
    name: "set"
    usage: "&6Usage: /money set <player> <quantity>."
    permission: "rtb.economy.admin"
    alias: ["s"]
  remove:
    name: "remove"
    usage: "&6Usage: /money remove <player> <quantity>."
    permission: "rtb.economy.admin"
    alias: ["r"]
  pay:
    name: "pay"
    usage: "&6Usage: /money pay <player> <quantity>."
    permission: "rtb.economy.player"
    alias: ["p"]
  toggle:
    name: "toggle"
    usage: "&6Usage: /money toggle."
    permission: "rtb.economy.player"
    alias: ["t"]
  number-formatter:
    name: "format"
    usage: "&6Usage: /money format."
    permission: "rtb.economy.player"
    alias: ["formatter"]
  money-top:
    name: "top"
    usage: "&6Usage: /money top."
    permission: "rtb.economy.player"
    alias: ["moneytop", "balancetop", "top10"]
  config:
    name: "config"
    usage: "&6Usage: /money config."
    permission: "rtb.economy.player"
    alias: ["configuration"]

inventories:
  config:
    rows: 6
    title: "Player's config menu"
